{% set version = "0.14.1" %}

package:
  name: impyla
  version: {{ version }}

source:
  fn: impyla-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/impyla/impyla-{{ version }}.tar.gz
  md5: 4d9383ede4b0c36850fbec662c171bce
  patches:
    - 0001-Python-3.7.0-async-is-a-keyword.patch

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
    - six
    - bitarray
    - thrift  # [py2k]
    - thriftpy >=0.3.5

  run:
    - python
    - setuptools
    - six
    - bitarray
    - thriftpy >=0.3.5
    - thrift  # [py2k]

test:
  imports:
    - impala
    - impala.tests
    - impala.thrift
    - impala.hiveserver2

about:
  home: https://github.com/cloudera/impyla
  license: Apache 2.0
  license_family: Apache
  summary: 'Python client for the Impala distributed query engine'
  description: |
    Python DB API 2.0 client for Impala and Hive (HiveServer2 protocol)
  doc_url: https://pypi.python.org/pypi/impyla
  doc_source_url: https://github.com/cloudera/impyla/blob/master/README.md

extra:
  recipe-maintainers:
    - mariusvniekerk
    - wesm
