# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "m845KsbBf7sTdOPzUyBSfVCBcawcA/iYm/TSj8o81zfQiuzqpOdlJ0yJ97vjhmD23aesI6agW6p++3oOxkji/ts+eXB2M/qX+l7qxH9L6S/imWrHaxe7xutrwOeWg8HhmZU3XkEn0fCLOw8xfCKN6K9VJxtGyLDanT9mAy7LD6c52Gy+FA5XaV2QsrQnV4DCRkfdKHPyfJUbwq3fAfwwm0x3ltAwGwGzYErFqwjVgTP1Iq6g+/dy9UE0UjHe1ZqQ4dnwBqRn9DcOyl1zq9dL+DbL048eQ/1wilqUhDBjWxSJXx8swwLHqq8sPZ7C2viOff4DfKETwrF9V2ILw5I9Jr2OrlZsLJB4immL0P5VxJkn0VY2KEDle8YkAP0/BXtFUUl2x17hmb3LJNxx5xpLGy/kVcXG1N544lueOmkKt30zXAoF/4v2yA+T3d1S4fqqoR3zKyYvAL11OdbJ/NIQj8Ft3TFnSzJfNT0L26cmhhB3eRBhFNox0sfYbMhQoLQJVak+LOYmNzVWxl/+rXG5jdQKnymOjX4n+UBr+SS9vS+b9P4Y2A7qMjGMOGA7k0lOdcWhASFx6Gr28wBXjTP0QEjTrj8V3C06Odukcj3Ogr10sWsOWVvK8JL999DLw2EoSAZXlUqcUY0j9shQlGc+6bOKhSwMCN97A7Yf1qhy+oI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
