travis:
  secure:
    BINSTAR_TOKEN: 2p1WlOZEnYl5225TSfzh58gAzErrNaaS8b9jdZFw8qj5/HB921IGENL1wIMCsHAEv6xq97stq9gRriICqo1YKNWvTlYUyJrGUjTfgd+Q5eUFnulVuboPi8/ZW/09NBHBWTvS/Ku7Zz0m5lQpmE2ae86LW9ZQ22V9gFKxKMPOIii5PyrgoaDt5XMiGoRuUlezFwtyeUt6tRvm+9g05elNvWFlm4TGpaUcUnf5e0XV2beYl9NHV0hGfcZS6MndaBypeNpiq31JmaRz/XsItRETOZhthVskK6zQbQO9NnqaIgQNj1qGagc69nkCfUBIAYSHsQL8KXI+tnJfHCdvfVoRIkhVZKirMprvb9nUTGo71UeSJD+X7OdrrmUwi7z8gKwq106jeKYsCVUHsZqWBp8flETCHsQmYUfQDs9V445dEisMyFD3jUH16sesXsvvD5og7zM+x3oGEgzNIQYQwlsu2KAnMECJHJhi2ZnYNnwKxEIM7jwqpxF8+z3m59Mqg9swGdJFl4DtB0ErQgnOxs0uFSJjzUhoAUHia9ieCUuRwFowxmUw9jwkRp/XRrORbDI8mokxkx7Jb8WOTLO6yQFPjyeraF1HqnmrskcjaCSuKjV7bDZ9+BHeGUcdRVjfaInXXbn5xLuchtcj8jnj6jiy6Zrn/iB/31GMbSgL/6c4qQU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
