travis:
  secure:
    BINSTAR_TOKEN: m845KsbBf7sTdOPzUyBSfVCBcawcA/iYm/TSj8o81zfQiuzqpOdlJ0yJ97vjhmD23aesI6agW6p++3oOxkji/ts+eXB2M/qX+l7qxH9L6S/imWrHaxe7xutrwOeWg8HhmZU3XkEn0fCLOw8xfCKN6K9VJxtGyLDanT9mAy7LD6c52Gy+FA5XaV2QsrQnV4DCRkfdKHPyfJUbwq3fAfwwm0x3ltAwGwGzYErFqwjVgTP1Iq6g+/dy9UE0UjHe1ZqQ4dnwBqRn9DcOyl1zq9dL+DbL048eQ/1wilqUhDBjWxSJXx8swwLHqq8sPZ7C2viOff4DfKETwrF9V2ILw5I9Jr2OrlZsLJB4immL0P5VxJkn0VY2KEDle8YkAP0/BXtFUUl2x17hmb3LJNxx5xpLGy/kVcXG1N544lueOmkKt30zXAoF/4v2yA+T3d1S4fqqoR3zKyYvAL11OdbJ/NIQj8Ft3TFnSzJfNT0L26cmhhB3eRBhFNox0sfYbMhQoLQJVak+LOYmNzVWxl/+rXG5jdQKnymOjX4n+UBr+SS9vS+b9P4Y2A7qMjGMOGA7k0lOdcWhASFx6Gr28wBXjTP0QEjTrj8V3C06Odukcj3Ogr10sWsOWVvK8JL999DLw2EoSAZXlUqcUY0j9shQlGc+6bOKhSwMCN97A7Yf1qhy+oI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
